# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Vercel Action
        # You may pin to the exact commit or the version.
        # uses: amondnet/vercel-action@9001bb7086d6c5414c4f8e500a89e8fa632eaefe
        uses: amondnet/vercel-action@v25.1.0
        with:
          # Vercel token
          vercel-token:
          #
          vercel-args: true
          # if you want to comment on pr and commit, set true, default: true
          github-comment: true
          # if you want to comment on pr and commit, set token
          github-token: # optional
          # if you want to create github deployment, set true, default: false
          github-deployment: # optional, default is false
          # the working directory
          working-directory: # optional
          # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
          vercel-project-id: # optional
          # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
          vercel-org-id: # optional
          # The name of the project; if absent we'll use the `vercel inspect` command to determine.
          vercel-project-name: # optional
          # If you are work in team scope, you should set this value to your team id.
          scope: # optional
          # zeit.co token
          zeit-token:
          #
          now-args: # optional, default is
          # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
          now-project-id: # optional
          # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
          now-org-id: # optional
          # You can assign a domain to this deployment. Please note that this domain must have been configured in the project. You can use pull request number via `{{PR_NUMBER}}` and branch via `{{BRANCH}}`
          alias-domains: # optional, default is

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
